implemented executer service to send the large chunk in threads
boundary/remedy-tsi-integration-lib pull request #16
Opened 2017-08-04 04:49 UTC by vitiwari

@gokumar 
Implemented to send the events in multiple threads(Thread pool 20) with 30 events in each thread.

2017-08-08 10:56 UTC, gokumar requested changes

2017-08-08 10:56 UTC, gokumar commented on src/main/java/com/bmc/truesight/saas/remedy/integration/impl/CallableBulkEventHttpClient.java
> +            String jsonInString = null;
I guess, you can initialize httpPost outside loop and reuse the same object every time with new entity

what say?

2017-08-08 10:56 UTC, gokumar commented on src/main/java/com/bmc/truesight/saas/remedy/integration/impl/EventIngestionAsync.java
> +public class EventIngestionAsync {
Are we using this class yet?

2017-08-09 04:20 UTC, vitiwari commented on src/main/java/com/bmc/truesight/saas/remedy/integration/impl/EventIngestionAsync.java
> +public class EventIngestionAsync {
No, You want me to remove it ?

2017-08-09 04:23 UTC, gokumar commented on src/main/java/com/bmc/truesight/saas/remedy/integration/impl/EventIngestionAsync.java
> +public class EventIngestionAsync {
Please go ahead.

2017-08-09 11:25 UTC, gokumar approved these changes

2017-08-11 09:39 UTC, merged